blog/blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/mainapp/urls.py
from django.urls import path, include 
from django.contrib.auth import views as auth_views
from django.shortcuts import redirect
from . import views
from .views import logout_view

def my_login_view(request):
    response = auth_views.LoginView.as_view()(request)
    if request.user.is_authenticated:
        return redirect('admin:index')
    return response

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/login/', my_login_view, name='login'),
    path('signup/', views.signup, name='signup'),
    path('search/', views.search, name='search'),
    path('createpost/', views.create_post_view, name='createpost'),
    path('posty/', views.post_list, name='post_list'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('captcha/', include('captcha.urls')),
    path('post/<int:post_id>/add_comment/', views.add_comment, name='add_comment'),
    path('logout/', logout_view, name='logout'),
    path('search/', views.search, name='search')
]

blog/mainapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Model dla użytkowników
class Uzytkownik(models.Model):
    nazwa_uzytkownika = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    haslo = models.CharField(max_length=100)
    rola = models.CharField(
        max_length=20, 
        choices=[
            ('Uzytkownik', 'Uzytkownik'), 
            ('Moderator', 'Moderator'), 
            ('Administrator', 'Administrator')
        ]
    )

    def __str__(self):
        return self.nazwa_uzytkownika

# Model dla postów
class Post(models.Model):
    tytul = models.CharField(max_length=200)
    tresc = models.TextField(max_length=2000)
    data_utworzenia = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True, upload_to="images/")
    
    DOSTEP_CHOICES = (
        ('Publiczny', 'Publiczny'),
        ('Ograniczony', 'Ograniczony'),
    )
    dostep = models.CharField(max_length=20, choices=DOSTEP_CHOICES, default='Publiczny')

    def __str__(self):
        return self.tytul

# Model dla komentarzy
class Komentarz(models.Model):
    tresc = models.TextField()
    data_dodania = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f"Komentarz do {self.post.tytul}"

# Model dla elementów graficznych
class ElementGraficzny(models.Model):
    url = models.URLField()
    opis = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f"Element graficzny dla {self.post.tytul}"

blog/mainapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post, Komentarz
from captcha.fields import CaptchaField

# Formularz rejestracji użytkownika
class SignUpForm(UserCreationForm):
    # Pole dla nazwy użytkownika
    username = forms.CharField(
        label='username', 
        min_length=5, 
        max_length=150, 
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    # Pole dla adresu email
    email = forms.EmailField(
        label='email', 
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )
    # Pole dla hasła
    password1 = forms.CharField(
        label='password', 
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    # Pole do powtórzenia hasła
    password2 = forms.CharField(
        label='Confirm password', 
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    # Pole CAPTCHA
    captcha = CaptchaField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

# Formularz tworzenia posta
class CreatePostForm(forms.ModelForm):
    # Pole dla tytułu posta
    title = forms.CharField(
        label='Tytuł', 
        min_length=5, 
        max_length=20, 
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    # Pole dla treści posta
    description = forms.CharField(
        label='Treść', 
        min_length=20, 
        max_length=2000, 
        widget=forms.Textarea(attrs={'class': 'form-control'})
    )
    # Pole dla wyboru dostępu
    dostep = forms.ChoiceField(
        label='Dostęp', 
        choices=Post.DOSTEP_CHOICES, 
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Post
        fields = ('title', 'description', 'image', 'dostep')

# Formularz tworzenia komentarza
class CreateCommentForm(forms.ModelForm):
    # Pole dla treści komentarza
    comment = forms.CharField(
        label='Komentarz', 
        widget=forms.Textarea(attrs={'rows': 4, 'class': 'form-control'})
    )

    class Meta:
        model = Komentarz
        fields = ('comment',)

blog/mainapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from .forms import SignUpForm, CreatePostForm, CreateCommentForm  # Import formularzy
from .models import Post, Komentarz  # Import modeli
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views.decorators.http import require_POST
from captcha.fields import CaptchaField  # Import CaptchaField


# Widok przekierowujący na listę postów
def index(request):
    return redirect('post_list')


# Widok rejestracji użytkownika
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            print("dodano uzytkownika")
            return redirect('login')

    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})


# Widok wyszukiwania postów
def search(request):
    query = request.GET.get('q')
    if query:
        posts = Post.objects.filter(tytul__icontains=query)
    else:
        posts = Post.objects.all()
    return render(request, 'search_results.html', {'posts': posts, 'query': query})


# Widok tworzenia nowego postu
@login_required
def create_post_view(request):
    if request.method == 'POST':
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.autor = request.user
            post.save()
            print("dodano post")
            return redirect('post_list')

    else:
        form = CreatePostForm()
    return render(request, './post/postForm.html', {'form': form})


# Widok listy postów
def post_list(request):
    if request.user.is_authenticated:
        posts = Post.objects.all()
    else:
        posts = Post.objects.filter(dostep='Publiczny')
    print("wyswietlono liste postow")
    return render(request, './post/post_list.html', {'posts': posts})


# Widok szczegółów postu
def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    print("sprawdzono szczeguły posta")
    return render(request, 'post/post_detail.html', {'post': post})


# Przykładowy widok, może być używany do czegoś innego
def some_view(request):
    if request.POST:
        form = CaptchaTestForm(request.POST)
        if form.is_valid():
            human = True
    else:
        form = CaptchaTestForm()

    return render(request, 'template.html', {'form': form})


# Widok wylogowania użytkownika
@require_POST
def logout_view(request):
    logout(request)
    return redirect('index')


# Widok dodawania komentarzy
@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CreateCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.tresc = form.cleaned_data['comment']
            comment.autor = request.user
            comment.post = post
            comment.save()
            print("dodano komentarz")
            return redirect('post_detail', post_id=post_id)
    else:
        form = CreateCommentForm()
    return redirect('post_detail', post_id=post_id)

# Widok szczegółów postu z uwzględnieniem komentarzy
def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = Komentarz.objects.filter(post=post).order_by('-data_dodania')
    form = CreateCommentForm()
    print("wyswietlono szczegoly posta")
    return render(request, 'post/post_detail.html', {'post': post, 'comments': comments, 'form': form})


# Widok wyszukiwania postów
def search(request):
    if request.method == "POST":
        searched = request.POST.get('searched')

        if request.user.is_authenticated:
            post = Post.objects.filter(tytul__contains=searched)
        else:
            post = Post.objects.filter(dostep='Publiczny', tytul__contains=searched)
        print('uzyto wyszukiwarki')

        return render(request, 'post/search.html', {'searched': searched, 'post': post})
    else:
        return render(request, 'post/search.html', {})

blog/mainapp/templates/post/postForm.html
{% extends "base.html" %}

{% block title %}Stwórz post{% endblock %}

{% block content %}
<div class="container mt-5 d-flex justify-content-center align-items-center" style="min-height: 100vh;">
  <div class="row justify-content-center w-100">
    <div class="col-md-8">
      <div class="card border-light shadow-sm">
        <div class="card-body">
          <!-- Nagłówek formularza -->
          <h2 class="card-title text-center mb-4">Stwórz post</h2>
          <!-- Formularz do tworzenia postu -->
          <form method="post" enctype="multipart/form-data">
            <!-- Token CSRF do zabezpieczenia formularza -->
            {% csrf_token %}
            <!-- Pole tytułu postu -->
            <div class="form-group mb-4">
                <label for="id_title" class="fs-5">Tytuł:</label>
                {{ form.title }}
                <!-- Wyświetlanie błędów walidacji dla pola tytułu -->
                {% if form.title.errors %}
                <div class="invalid-feedback d-block">
                    {{ form.title.errors|join:", " }}
                </div>
                {% endif %}
            </div>
            <!-- Pole treści postu -->
            <div class="form-group mb-4">
                <label for="id_description" class="fs-5">Treść:</label>
                {{ form.description }}
                <!-- Wyświetlanie błędów walidacji dla pola treści -->
                {% if form.description.errors %}
                <div class="invalid-feedback d-block">
                    {{ form.description.errors|join:", " }}
                </div>
                {% endif %}
            </div>
            <!-- Pole dodawania zdjęcia -->
            <div class="form-group mb-4">
                <label for="id_image" class="fs-5">Zdjęcie:</label>
                {{ form.image }}
                <!-- Wyświetlanie błędów walidacji dla pola zdjęcia -->
                {% if form.image.errors %}
                <div class="invalid-feedback d-block">
                    {{ form.image.errors|join:", " }}
                </div>
                {% endif %}
            </div>
            <!-- Pole wyboru dostępności -->
            <div class="form-group mb-4">
                <label for="id_dostep" class="fs-5">Dostęp:</label>
                {{ form.dostep }}
                <!-- Wyświetlanie błędów walidacji dla pola dostępności -->
                {% if form.dostep.errors %}
                <div class="invalid-feedback d-block">
                    {{ form.dostep.errors|join:", " }}
                </div>
                {% endif %}
            </div>
            <!-- Przycisk wysyłania formularza -->
            <button type="submit" class="btn btn-primary mt-4 w-100 fs-5">Dodaj Post</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  .card {
    border: none;
    border-radius: 10px;
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
    margin-top: 10px;
    margin-bottom: 10px;
  }

  .card-title {
    font-size: 2rem;
    color: #343a40;
  }

  .card-body {
    padding: 40px;
  }

  .form-group label {
    font-weight: bold;
    color: #495057;
  }

  .form-group input,
  .form-group label,
  .form-group .form-control,
  .form-group .form-control-file,
  .form-group .custom-select {
    margin-top: 10px;
  }

  .form-group .fs-5 {
    font-size: 1.25rem;
  }

  .btn-primary {
    background-color: #6c757d;
    border: none;
  }

  .btn-primary:hover {
    background-color: #5a6268;
  }

  .invalid-feedback {
    color: red;
    font-size: 12px;
  }

  .form-group:not(:last-child) {
    margin-bottom: 1rem;
  }
</style>

<!-- Ładowanie CKEditor, edytora tekstu dla pola treści -->
<script src="https://cdn.ckeditor.com/4.16.0/standard/ckeditor.js"></script>
<script>
  CKEDITOR.replace('id_description', {
    height: 300,
    autoParagraph: false
  });
</script>
{% endblock %}

blog/mainapp/templates/post/post_detail.html
{% extends "base.html" %}

{% block title %}Szczegóły Posta{% endblock %}

{% block content %}
<style>
  .centered {
    text-align: center;
  }

  .big-title {
    font-size: 2rem;
    margin-bottom: 20px;
  }

  .big-author {
    font-size: 1.5rem;
    margin-bottom: 20px;
  }

  .post-content {
    display: flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 20px;
    text-align: center;
  }

  .post-content img {
    max-width: 50%;
    height: auto;
    margin-right: 20px;
  }

  .comment-section {
    margin-top: 40px;
  }

  .comment {
    border: 1px solid #000000;
    padding: 10px;
    margin-bottom: 20px;
    border-radius: 10px;
  }

  .comment-author {
    font-weight: bold;
    margin-bottom: 5px;
  }

  .comment-date {
    font-size: 0.8rem;
    color: #777;
    text-align: right;
  }

  .comment-form {
    margin-bottom: 40px;
  }

  .submit-btn {
    margin-top: 10px;
  }
</style>

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8 centered">
      <!-- Wyświetl tytuł posta -->
      <h2 class="big-title">{{ post.tytul }}</h2>
      <!-- Wyświetl autora posta -->
      <h4 class="big-author">Autor: {{ post.autor }}</h4>
      <div class="post-content">
        <!-- Sprawdź, czy post ma obrazek i wyświetl go, jeśli jest dostępny -->
        {% if post.image %}
        <img src="{{ post.image.url }}">
        {% endif %}
        <!-- Wyświetl treść posta -->
        <p>{{ post.tresc }}</p>
      </div>
      <!-- Wyświetl datę utworzenia posta -->
      <small>Data utworzenia: {{ post.data_utworzenia }}</small>

      <!-- Sekcja formularza komentarzy -->
      <div class="comment-form">
        <h3>Dodaj komentarz</h3>
        <!-- Formularz do dodawania komentarza, wysyłający dane do URL 'add_comment' -->
        <form id="comment-form" method="post" action="{% url 'add_comment' post.id %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="comment">Twój komentarz:</label>
            <!-- Renderowanie pola formularza komentarza -->
            {{ form.comment }}
          </div>
          <!-- Przycisk wysyłania formularza komentarza -->
          <button type="submit" class="btn btn-success submit-btn">Dodaj komentarz</button>
        </form>
      </div>

      <!-- Sekcja komentarzy wyświetlająca wszystkie komentarze -->
      <div class="comment-section">
        <h3>Komentarze</h3>
        <!-- Pętla przez każdy komentarz i jego wyświetlenie -->
        {% for comment in comments %}
        <div class="comment">
          <!-- Wyświetl autora komentarza -->
          <p class="comment-author">{{ comment.autor.username }}</p>
          <!-- Wyświetl treść komentarza -->
          <p>{{ comment.tresc }}</p>
          <!-- Wyświetl datę dodania komentarza -->
          <p class="comment-date">{{ comment.data_dodania }}</p>
        </div>
        {% endfor %}
      </div>

    </div>
  </div>
</div>

<script>
  // Dodaj nasłuchiwacz zdarzeń, aby przełączać widoczność formularza komentarzy
  document.getElementById("add-comment-button").addEventListener("click", function() {
    var commentForm = document.getElementById("comment-form");
    if (commentForm.style.display === "none") {
      commentForm.style.display = "block";
    } else {
      commentForm.style.display = "none";
    }
  });
</script>

{% endblock %}

blog/mainapp/templates/post/post_list.html
{% extends "base.html" %}

{% block title %}Lista Postów{% endblock %}

{% block content %}
<style>
  .post-card {
    border: 1px solid #191818;
    border-radius: 10px;
    margin-bottom: 20px;
    margin-top: 10px;
    width: 100%;
    height: 85%;
    overflow: hidden;
  }

  .post-title {
    font-size: 1.2rem;
    color: #000000;
    margin: 10px;
    text-align: center;
  }

  .post-text {
    font-size: 1rem;
    color: #050505;
    margin: 10px;
    overflow: hidden;
    height: 60%;
  }

  .post-image {
    max-width: 30%;
    max-height: 30%;
    margin: 20px auto;
    display: block;
  }

  .post-info {
    font-size: 0.9rem;
    color: #060606;
    margin: 10px;
  }

  .read-more-btn {
    background-color: #a9b1b9;
    color: #000000;
    border: none;
    margin: 10px;
    display: block;
  }

  .read-more-btn:hover {
    background-color: #515253;
  }

  .post-label {
    font-size: 1.5rem;
    font-weight: bold;
    color: #000000;
    text-align: center;
    margin-bottom: 20px;
  }

  @media (min-width: 768px) {
    .col-md-4 {
      flex: 0 0 calc(27% - 20px);
      max-width: calc(27% - 20px);
    }

    .row {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-around;
      margin-top: 10px;
      margin-bottom: 20px;
    }

    .col-md-4 {
      padding: 0 10px;
    }
  }
</style>

<div class="container mt-5">
  <!-- Nagłówek sekcji -->
  <h2 class="post-label">Lista Postów</h2>
  <div class="row justify-content-center">
    <!-- Pętla przez każdy post i jego wyświetlenie -->
    {% for post in posts %}
    <div class="col-md-4 mb-3">
      <!-- Karta z postem -->
      <div class="card post-card">
        <div class="card-body">
          <!-- Wyświetl tytuł posta -->
          <h5 class="card-title post-title">{{ post.tytul }}</h5>
          <!-- Wyświetl skróconą treść posta -->
          <p class="card-text post-text">{{ post.tresc|truncatewords_html:10 }}</p>
        </div>
        <div class="card-footer">
          <!-- Wyświetl autora posta -->
          <small class="text-muted post-info">Autor: {{ post.autor }}</small>
          <br>
          <!-- Wyświetl datę utworzenia posta -->
          <small class="text-muted post-info">Data utworzenia: {{ post.data_utworzenia }}</small>
        </div>
        <!-- Sprawdź, czy post ma obrazek i wyświetl go, jeśli jest dostępny -->
        {% if post.image %}
        <img src="{{ post.image.url }}" alt="{{ post.tytul }}" class="post-image">
        {% endif %}
        <!-- Przycisk przekierowujący do szczegółów posta -->
        <a href="{% url 'post_detail' post.id %}" class="btn btn-primary read-more-btn">Przeczytaj więcej</a>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

blog/mainapp/templates/post/search.html
<!-- index.html -->
{% extends 'base.html' %}

{% block title %}Strona główna{% endblock %}

{% block content %}
    {% if searched %}
        <h1>Wyszukiwarka postów</h1>
    {% for p in post %}

        <a href="{% url 'post_detail' p.id %}" >{{ p }} </a><br><br>
    {% endfor %}
    {% else %}
        <h1> Wpisz nazwe postu którego szukasz </h1>
    {% endif %}


{% endblock %}